In [2]:
import pandas as pd 
import numpy as np 

from sklearn import preprocessing

In [28]:
filepath = 'data/NBA_player_of_the_week.csv'
nb_player = pd.read_csv(filepath)
display(nb_player.info())
display(type(nb_player))
display(nb_player.head())
nb_player.describe(include='all')

<class 'pandas.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Player             1340 non-null   str
 1   Team               1340 non-null   str
 2   Conference         839 non-null    str
 3   Date               1340 non-null   str
 4   Position           1340 non-null   str
 5   Height             1340 non-null   str
 6   Weight             1340 non-null   int64
 7   Age                1340 non-null   int64
 8   Draft Year         1340 non-null   int64
 9   Seasons in league  1340 non-null   int64
 10  Season             1340 non-null   str
 11  Season short       1340 non-null   int64
 12  Pre-draft Team     1340 non-null   str
 13  Real_value         1340 non-null   float64
 14  Height CM          1340 non-null   int64
 15  Weight KG          1340 non-null   int64
 16  Last Season        1340 non-null   int64
dtypes: float64(1), int64(8), str(8)
memory usage: 178.1 KB

None

pandas.DataFrame

,Player,Team,Conference,Date,Position,Height,Weight,Age,Draft Year,Seasons in league,Season,Season short,Pre-draft Team,Real_value,Height CM,Weight KG,Last Season
0,Jayson Tatum,Boston Celtics,East,"Feb 10, 2020",SF,6'8,208,21,2017,2,2019-2020,2020,Duke,0.5,203,94,1
1,Nikola Jokic,Denver Nuggets,West,"Feb 10, 2020",C,7'0,250,25,2014,4,2019-2020,2020,KK Mega Bemax (Serbia),0.5,213,113,1
2,Jaylen Brown,Boston Celtics,East,"Feb 3, 2020",SF,6'7,220,23,2016,3,2019-2020,2020,California,0.5,201,99,1
3,Damian Lillard,Portland Trail Blazers,West,"Feb 3, 2020",G,6'3,195,29,2012,7,2019-2020,2020,Weber State,0.5,190,88,1
4,Pascal Siakam,Toronto Raptors,East,"Jan 27, 2020",F,6'9,230,25,2016,3,2019-2020,2020,New Mexico State,0.5,206,104,1

,Player,Team,Conference,Date,Position,Height,Weight,Age,Draft Year,Seasons in league,Season,Season short,Pre-draft Team,Real_value,Height CM,Weight KG,Last Season
count,1340,1340,839,1340,1340,1340,1340.000000,1340.000000,1340.000000,1340.000000,1340,1340.000000,1340,1340.000000,1340.000000,1340.000000,1340.000000
unique,333,37,2,916,11,21,NaN,NaN,NaN,NaN,41,NaN,169,NaN,NaN,NaN,NaN
top,LeBron James,Los Angeles Lakers,East,"Jan 12, 2003",G,6'9,NaN,NaN,NaN,NaN,2002-2003,NaN,St. Vincent St. Mary High School (Ohio),NaN,NaN,NaN,NaN
freq,63,87,420,3,200,158,NaN,NaN,NaN,NaN,47,NaN,63,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,224.567164,26.738060,1996.287313,5.740299,NaN,2003.156716,NaN,0.686940,201.071642,101.384328,0.023881
std,NaN,NaN,NaN,NaN,NaN,NaN,30.798885,3.400683,11.253558,3.293421,NaN,11.470164,NaN,0.242007,9.367970,14.011226,0.152734
min,NaN,NaN,NaN,NaN,NaN,NaN,150.000000,19.000000,1965.000000,0.000000,NaN,1980.000000,NaN,0.500000,175.000000,68.000000,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,205.000000,24.000000,1987.000000,3.000000,NaN,1994.000000,NaN,0.500000,193.000000,93.000000,0.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,220.000000,26.000000,1998.000000,5.000000,NaN,2005.000000,NaN,0.500000,201.000000,99.000000,0.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,250.000000,29.000000,2005.000000,8.000000,NaN,2013.000000,NaN,1.000000,208.000000,113.000000,0.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,325.000000,40.000000,2018.000000,17.000000,NaN,2020.000000,NaN,1.000000,229.000000,147.000000,1.000000

In [23]:
height_weight_age_df = nb_player[['Height CM', 'Weight KG', 'Age']]
type(height_weight_age_df)

pandas.DataFrame

In [6]:
height_weight_age_df

      Height CM  Weight KG  Age
0           203         94   21
1           213        113   25
2           201         99   23
3           190         88   29
4           206        104   25
...         ...        ...  ...
1335        188         79   24
1336        206        115   20
1337        201         98   24
1338        196         85   24
1339        198         90   30

[1340 rows x 3 columns]

In [27]:
height_weight_age_df.isna().sum()

Height CM    0
Weight KG    0
Age          0
dtype: int64

In [45]:
scaler = preprocessing.MinMaxScaler()  ##객체 생성
normalized_data = scaler.fit_transform(height_weight_age_df) ## 스케일링
normalized_df = pd.DataFrame(normalized_data, columns=['Height', 'Weight', 'Age'])
display(normalized_df.describe())
display(normalized_df)

          Height     Weight        Age
count 1340.00000 1340.00000 1340.00000
mean     0.48281    0.42259    0.36848
std      0.17348    0.17736    0.16194
min      0.00000    0.00000    0.00000
25%      0.33333    0.31646    0.23810
50%      0.48148    0.39241    0.33333
75%      0.61111    0.56962    0.47619
max      1.00000    1.00000    1.00000

      Height  Weight     Age
0    0.51852 0.32911 0.09524
1    0.70370 0.56962 0.28571
2    0.48148 0.39241 0.19048
3    0.27778 0.25316 0.47619
4    0.57407 0.45570 0.28571
...      ...     ...     ...
1335 0.24074 0.13924 0.23810
1336 0.57407 0.59494 0.04762
1337 0.48148 0.37975 0.23810
1338 0.38889 0.21519 0.23810
1339 0.42593 0.27848 0.52381

[1340 rows x 3 columns]

In [ ]:
from sklearn import preprocessing
import pandas as pd 
import numpy as np 

filepath = 'data/NBA_player_of_the_week.csv' 
nba_player = pd.read_csv(filepath)
#pd.set_option('display.float_format', lambda x : '%.5f' %x)

height_weight_age_df = nba_player[['Height CM', 'Weight KG', 'Age' ]]
type(height_weight_age_df)
##표준화
scaler = preprocessing.StandardScaler()
std_data = scaler.fit_transform(height_weight_age_df )
display(std_data)
std_df = pd.DataFrame(std_data, columns=['Height', 'Weight', 'Age' ])
display(std_df)
std_df.describe()

array([[ 0.20592274, -0.52722617, -1.68795564],
       [ 1.27378837,  0.82933556, -0.51128218],
       [-0.00765038, -0.17023624, -1.09961891],
       ...,
       [-0.00765038, -0.24163423, -0.80545055],
       [-0.54158319, -1.16980804, -0.80545055],
       [-0.32801007, -0.81281811,  0.95955965]], shape=(1340, 3))

       Height   Weight      Age
0     0.20592 -0.52723 -1.68796
1     1.27379  0.82934 -0.51128
2    -0.00765 -0.17024 -1.09962
3    -1.18230 -0.95561  0.66539
4     0.52628  0.18675 -0.51128
...       ...      ...      ...
1335 -1.39588 -1.59820 -0.80545
1336  0.52628  0.97213 -1.98212
1337 -0.00765 -0.24163 -0.80545
1338 -0.54158 -1.16981 -0.80545
1339 -0.32801 -0.81282  0.95956

[1340 rows x 3 columns]

          Height     Weight        Age
count 1340.00000 1340.00000 1340.00000
mean    -0.00000   -0.00000   -0.00000
std      1.00037    1.00037    1.00037
min     -2.78410   -2.38357   -2.27629
25%     -0.86194   -0.59862   -0.80545
50%     -0.00765   -0.17024   -0.21711
75%      0.73986    0.82934    0.66539
max      2.98237    3.25687    3.90124