In [1]:
import pandas as pd

loan_df = pd.read_csv('data/loan.csv')
loan_df = loan_df.set_index('loan_id')
new_columns = {'married_or_not': 'married',
               'self_employed_or_not': 'self_employed',
               'applicant_income': 'income',
               'loan_amount': 'amount'                
}
##컬럼 이름 변경
loan_df = loan_df.rename(columns=new_columns)
####income컬럼 형변환
loan_df['income'].astype('float')
loan_df

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N    4583   128.4         Rural           N
LP1005        Y             Y    3000    66.0          City           Y
LP1006        Y             N    2583   120.5          City           Y
LP1008        N             N    6000   141.4          City           Y
LP1011        Y             Y    5417   267.4          City           Y
...         ...           ...     ...     ...           ...         ...
LP2974        Y             N    3232   108.6         Rural           Y
LP2979        Y             N    4106    40.7         Rural           Y
LP2983        Y             N    8072   253.4          City           Y
LP2984        Y             N    7583   187.6          City           Y
LP2990        N             Y    4583   133.2        Suburb           N

[600 rows x 6 columns]

In [4]:
loan_df.query("property_area not in ['City', 'Suburb']")

        married self_employed  income  amount property_area loan_status
loan_id
LP1003        Y             N    4583   128.4         Rural           N
LP1029        N             N    1853   114.1         Rural           N
LP1038        Y             N    4887   133.5         Rural           N
LP1050        Y             N    3365   112.4         Rural           N
LP1097        N             Y    4692   106.2         Rural           N
...         ...           ...     ...     ...           ...         ...
LP2950        Y           NaN    2894   155.5         Rural           Y
LP2958        N             N    3676   172.3         Rural           Y
LP2964        Y             N    3987   157.3         Rural           Y
LP2974        Y             N    3232   108.6         Rural           Y
LP2979        Y             N    4106    40.7         Rural           Y

[175 rows x 6 columns]

In [ ]:
income_mean = loan_df['income'].mean()
loan_df.query("(married == 'Y') & (income > @income_mean)")

        married self_employed  income  amount property_area loan_status
loan_id
LP1011        Y             Y    5417   267.4          City           Y
LP1020        Y             N   12841   349.3        Suburb           N
LP1043        Y             N    7660   104.1          City           N
LP1046        Y             N    5955   315.5          City           Y
LP1066        Y             Y    9560   191.1        Suburb           Y
...         ...           ...     ...     ...           ...         ...
LP2948        Y             N    5780   192.9          City           Y
LP2953        Y             N    5703   128.5          City           Y
LP2959        Y             N   12000   497.0        Suburb           Y
LP2983        Y             N    8072   253.4          City           Y
LP2984        Y             N    7583   187.6          City           Y

[120 rows x 6 columns]