In [52]:
##효준이는 새로운 스마트폰을 구입하기 위해 애플과 삼성의 스마트폰 데이터를 수집했습니다. 
# 그런데 실수로 특정 모델의 무게를 입력하는 것을 깜빡했다고 하는데요. 
# 다행히 한 가지 모델만 누락되어 있고, 모델명이 같으면 용량이나 색상과 관계없이 무게가 동일하다고 합니다. 
# 아래 표를 참고해서 cellphone_df에 있는 결측값을 올바른 값으로 채워 주세요. 
# 그 다음에는 cellphone_df에서 2021년에 출시한 스마트폰들의 데이터만 출력해 주세요.

import pandas as pd

cellphone_df = pd.read_csv('data/cellphone.csv')

# 여기에 코드를 작성하세요.
##결측값 확인
print(cellphone_df.info())
print(cellphone_df.isna().sum())
cellphone_df[cellphone_df.isna().any(axis=1)]

<class 'pandas.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   brand    70 non-null     str
 1   name     70 non-null     str
 2   size     70 non-null     str
 3   price    70 non-null     float64
 4   battery  70 non-null     int64
 5   weight   67 non-null     float64
 6   year     70 non-null     int64
dtypes: float64(2), int64(2), str(3)
memory usage: 6.1 KB
None
brand      0
name       0
size       0
price      0
battery    0
weight     3
year       0
dtype: int64

    brand                    name  size   price  battery  weight  year
37  Apple  iPhone 13 mini (128GB)  5.4"   950.0     2406     NaN  2021
38  Apple  iPhone 13 mini (256GB)  5.4"  1090.0     2406     NaN  2021
39  APPLE  iPhone 13 mini (512GB)  5.4"  1360.0     2406     NaN  2021

In [ ]:
##결측값 채우기
cellphone_df['weight'] = cellphone_df['weight'].fillna(140)

In [ ]:
cellphone_df[cellphone_df['year']==2021]

,brand,name,size,price,battery,weight,year
26,apple,iPhone 13 (128GB),"6.1""",1090.0,3227,173.0,2021
27,Apple,iPhone 13 (256GB),"6.1""",1230.0,3227,173.0,2021
28,apple,iPhone 13 (512GB),"6.1""",1500.0,3227,173.0,2021
29,APPLE,iPhone 13 Pro (128GB),"6.1""",1350.0,3095,203.0,2021
30,Apple,iPhone 13 Pro (256GB),"6.1""",1490.0,3095,203.0,2021
31,Apple,iPhone 13 Pro (512GB),"6.1""",1760.0,3095,203.0,2021
32,Apple,iPhone 13 Pro (1TB),"6.1""",2030.0,3095,203.0,2021
33,apple,iPhone 13 Pro Max (128GB),"6.7""",1490.0,4352,238.0,2021
34,Apple,iPhone 13 Pro Max (256GB),"6.7""",1630.0,4352,238.0,2021
35,Apple,iPhone 13 Pro Max (512GB),"6.7""",1900.0,4352,238.0,2021
36,Apple,iPhone 13 Pro Max (1TB),"6.7""",2170.0,4352,238.0,2021
37,Apple,iPhone 13 mini (128GB),"5.4""",950.0,2406,140,2021
38,Apple,iPhone 13 mini (256GB),"5.4""",1090.0,2406,140,2021
39,APPLE,iPhone 13 mini (512GB),"5.4""",1360.0,2406,140,2021
40,SAMSUNG,Galaxy A12 (32GB),"6.5""",275.0,5000,205.0,2021
41,samsung,Galaxy S21 (256GB),"6.2""",999.9,4000,169.0,2021
42,SAMSUNG,Galaxy S21 Ultra (256GB),"6.8""",1452.0,5000,227.0,2021
43,samsung,Galaxy S21 Ultra (512GB),"6.8""",1599.4,5000,227.0,2021
44,SAMSUNG,Galaxy S21+ (256GB),"6.7""",1199.0,4800,200.0,2021
45,SAMSUNG,Galaxy Z Flip3 (256GB),"6.7""",1254.0,3300,183.0,2021
46,Samsung,Galaxy Z Fold3 (256GB),"7.6""",1998.7,4400,271.0,2021
47,samsung,Galaxy Z Fold3 (512GB),"7.6""",2097.7,4400,271.0,2021
48,samsung,Galaxy Z Fold3 Thom Browne Edition (512GB),"7.6""",3960.0,4400,271.0,2021