## 비만도를 나타내는 지표로 'BMI(Body Mass Index)'라는 것도 많이 사용합니다. 
BMI를 계산하려면 몸무게(kg)를 키(m)의 제곱으로 나눠 주면 되는데요. 
예를 들어, 키가 180cm이고, 몸무게가 70kg인 사람의 BMI는 70을 1.8의 제곱으로 나눈 값인 21.6입니다.

위 내용을 참고해서 patient_df에 있는 각 환자의 BMI 값을 계산해서 bmi라는 컬럼에 저장해 주세요. 단, BMI 값은 소수 첫째 자리까지 반올림해 주셔야 합니다.

In [3]:
import pandas as pd 

patient_df = pd.read_csv('data/patient.csv')

patient_df.dtypes
patient_df

     age     sex  glucose  cholesterol  height  weight  hip  waist diabetes
0     50    Male      385          140    1.75    78.0   41     37        Y
1     37  Female       67          214    1.63    65.8   42     34        N
2     43  Female      100          160    1.63    63.5   40     37        N
3     32  Female       90          176    1.60   114.3   58     45        N
4     20    Male       71          164    1.83    65.8   36     29        N
..   ...     ...      ...          ...     ...     ...  ...    ...      ...
343   40    Male       87          218    1.85    90.7   41     38        N
344   66    Male      174          188    1.73    95.3   48     45        N
345   31  Female       69          183    1.68    86.2   47     41        N
346   44    Male       84          202    1.73    71.2   37     33        N
347   40  Female       85          169    1.65    81.6   44     40        N

[348 rows x 9 columns]

In [12]:
patient_df['bmi'] = round(patient_df['weight'] / patient_df['height']**2 , 1)
patient_df

,age,sex,glucose,cholesterol,height,weight,hip,waist,diabetes,bmi
0,50,Male,385,140,1.75,78.0,41,37,Y,25.5
1,37,Female,67,214,1.63,65.8,42,34,N,24.8
2,43,Female,100,160,1.63,63.5,40,37,N,23.9
3,32,Female,90,176,1.60,114.3,58,45,N,44.6
4,20,Male,71,164,1.83,65.8,36,29,N,19.6
...,...,...,...,...,...,...,...,...,...,...
343,40,Male,87,218,1.85,90.7,41,38,N,26.5
344,66,Male,174,188,1.73,95.3,48,45,N,31.8
345,31,Female,69,183,1.68,86.2,47,41,N,30.5
346,44,Male,84,202,1.73,71.2,37,33,N,23.8
347,40,Female,85,169,1.65,81.6,44,40,N,30.0