## weight 컬럼이 0과 1 사이의 값을 가지도록 정규화(Min Max Normalization)를 해 주세요.
== Min Max Scaling

In [1]:
import pandas as pd 

patient_df = pd.read_csv('data/patient.csv')
patient_df

     age     sex  glucose  cholesterol  height  weight  hip  waist diabetes
0     50    Male      385          140    1.75    78.0   41     37        Y
1     37  Female       67          214    1.63    65.8   42     34        N
2     43  Female      100          160    1.63    63.5   40     37        N
3     32  Female       90          176    1.60   114.3   58     45        N
4     20    Male       71          164    1.83    65.8   36     29        N
..   ...     ...      ...          ...     ...     ...  ...    ...      ...
343   40    Male       87          218    1.85    90.7   41     38        N
344   66    Male      174          188    1.73    95.3   48     45        N
345   31  Female       69          183    1.68    86.2   47     41        N
346   44    Male       84          202    1.73    71.2   37     33        N
347   40  Female       85          169    1.65    81.6   44     40        N

[348 rows x 9 columns]

In [7]:
patient_df['weight'] = (patient_df['weight'] - patient_df['weight'].min() ) /  \
                        (patient_df['weight'].max() - patient_df['weight'].min() )

In [9]:
patient_df['height'] = (patient_df['height'] - patient_df['height'].min() ) /  \
                        (patient_df['height'].max() - patient_df['height'].min() ) 
patient_df

,age,sex,glucose,cholesterol,height,weight,hip,waist,diabetes
0,50,Male,385,140,0.704918,0.322927,41,37,Y
1,37,Female,67,214,0.508197,0.203902,42,34,N
2,43,Female,100,160,0.508197,0.181463,40,37,N
3,32,Female,90,176,0.459016,0.677073,58,45,N
4,20,Male,71,164,0.836066,0.203902,36,29,N
...,...,...,...,...,...,...,...,...,...
343,40,Male,87,218,0.868852,0.446829,41,38,N
344,66,Male,174,188,0.672131,0.491707,48,45,N
345,31,Female,69,183,0.590164,0.402927,47,41,N
346,44,Male,84,202,0.672131,0.256585,37,33,N
347,40,Female,85,169,0.540984,0.358049,44,40,N