## 실습 설명
이번에는 배달 음식이 고객에게 도착한 시각을 계산해 봅시다. 
주문 시각(order_time)과 배달 소요 시간(time_taken)을 가지고 배달 완료 시간을 계산해서 DataFrame에 delivery_time 이라는 컬럼을 추가해 주세요! 참고로 time_taken 컬럼은 배달에 몇 분이 소요되었는지를 의미하므로, 아래 출력 결과처럼 분을 기준으로 한 Timedelta로 바꿔 주세요. 참고로 분을 의미하는 코드는 T 입니다.

In [20]:
import pandas as pd

delivery_df = pd.read_csv('data/delivery.csv', parse_dates=['order_time'])

In [21]:
delivery_df.dtypes

order_time           datetime64[us]
distance                    float64
time_taken                    int64
num_of_deliveries             int64
charge                      float64
dtype: object

In [22]:
delivery_df['order_time'] = pd.to_datetime(delivery_df['order_time'])
delivery_df['time_taken'] = pd.to_timedelta(delivery_df['time_taken'] , unit='m') 
delivery_df['delivery_time'] = delivery_df['order_time'] + delivery_df['time_taken']
delivery_df

,order_time,distance,time_taken,num_of_deliveries,charge,delivery_time
0,2022-10-17 18:34:00,3.9,0 days 00:21:00,1,4.68,2022-10-17 18:55:00
1,2022-10-17 18:35:00,5.2,0 days 00:24:00,1,7.02,2022-10-17 18:59:00
2,2022-10-17 18:36:00,8.4,0 days 00:36:00,2,9.53,2022-10-17 19:12:00
3,2022-10-17 18:37:00,3.6,0 days 00:17:00,1,6.21,2022-10-17 18:54:00
4,2022-10-17 18:41:00,2.6,0 days 00:15:00,1,2.44,2022-10-17 18:56:00
...,...,...,...,...,...,...
104,2022-10-23 19:28:00,6.4,0 days 00:37:00,1,5.01,2022-10-23 20:05:00
105,2022-10-23 19:28:00,3.9,0 days 00:26:00,2,7.34,2022-10-23 19:54:00
106,2022-10-23 19:48:00,3.3,0 days 00:21:00,1,3.83,2022-10-23 20:09:00
107,2022-10-23 19:49:00,5.8,0 days 00:22:00,1,5.80,2022-10-23 20:11:00
108,2022-10-23 19:50:00,4.4,0 days 00:19:00,1,7.78,2022-10-23 20:09:00

In [15]:
pd.to_timedelta(delivery_df['time_taken'] , unit='m')

0     0 days 00:21:00
1     0 days 00:24:00
2     0 days 00:36:00
3     0 days 00:17:00
4     0 days 00:15:00
            ...
104   0 days 00:37:00
105   0 days 00:26:00
106   0 days 00:21:00
107   0 days 00:22:00
108   0 days 00:19:00
Name: time_taken, Length: 109, dtype: timedelta64[s]

In [8]:
delivery_df

             order_time  distance  time_taken  num_of_deliveries  charge
0   2022-10-17 18:34:00       3.9          21                  1    4.68
1   2022-10-17 18:35:00       5.2          24                  1    7.02
2   2022-10-17 18:36:00       8.4          36                  2    9.53
3   2022-10-17 18:37:00       3.6          17                  1    6.21
4   2022-10-17 18:41:00       2.6          15                  1    2.44
..                  ...       ...         ...                ...     ...
104 2022-10-23 19:28:00       6.4          37                  1    5.01
105 2022-10-23 19:28:00       3.9          26                  2    7.34
106 2022-10-23 19:48:00       3.3          21                  1    3.83
107 2022-10-23 19:49:00       5.8          22                  1    5.80
108 2022-10-23 19:50:00       4.4          19                  1    7.78

[109 rows x 5 columns]